Removed the Requirement for Root in GitHub Installation
openSUSE/suse-vale-styleguide pull request #100
Opened 2024-06-19 14:47 UTC by alexvonme

I think we shouldn't suggest using sudo with binaries unless we have to. I tried to follow best practice while keeping it simple.

2024-06-20 07:34 UTC, tomschr requested changes
I have an idea (see below), let's discuss that together.

2024-06-20 07:34 UTC, tomschr commented on README.md
> +source .bashrc
> I think we shouldn't suggest using sudo with binaries unless we have to. I tried to follow best practice while keeping it simple.

That's a good point. :+1:

However, adding `./vale` to PATH is dangerous. What if users have a `vale` directory in their current directory? Suddenly, Vale wouldn't work anymore, right?

I would suggest to use an absolute path somewhere in the user's directory. Could be `~/vale` or something else:

```suggestion
echo 'export PATH=~/vale:"$PATH"' >> .bashrc
source .bashrc
```

2024-06-20 08:11 UTC, alexvonme commented on README.md
> +source .bashrc
I agree, that's a good point. However, the earlier command also needs to be revised because we assume the user is in the home directory there as well.

2024-06-20 08:27 UTC, alexvonme commented
Apologies for the needless multiple updates. I somehow forgot how tar worked for a minute there.

How does it look now @tomschr ?

2024-06-20 08:39 UTC, tomschr commented
> Apologies for the needless multiple updates. I somehow forgot how tar worked for a minute there.

All fine, no worries. :slightly_smiling_face: 


> How does it look now @tomschr ?

That's perfect! :+1: Thank you very much!

2024-06-20 08:39 UTC, tomschr approved these changes

2024-06-20 08:41 UTC, alexvonme commented on README.md
> +tar xvf vale*.tar.gz -C $HOME/vale
I think ``vale*`` is a better idea here since there are multiple commands and in the earlier section we suggest getting the latest release which they would have to edit from the middle, making the whole process a bit more awkward. 

Alternatively we could write:
```shell
for file in vale*.tar.gz; do tar -xvf "$file" -C $HOME/vale; done
```
That way the command succeeds no matter how many vale archives are in the directory since they'll all be decompressed and the last version (the latest version) will be the new vale.

2024-06-21 07:54 UTC, tbazant requested changes
look good but we need to make it a bit consistent

2024-06-21 09:36 UTC, alexvonme commented on README.md
> +test -d $HOME/vale || mkdir $HOME/vale
``~`` is better

2024-06-21 09:43 UTC, alexvonme commented
@tbazant I've just changed the ``$HOME`` parts to ``~``. 

However, I don't think we need to urgently unify everything in README just yet. I think at present, we ought to focus on functionality and completing the ruleset. Depending on the rules, the README will likely require further updates anyway.

2024-06-24 07:52 UTC, tbazant approved these changes
looks good, thanks

2024-06-24 07:53 UTC, merged