Fix Spacing in Latin.yml
openSUSE/suse-vale-styleguide pull request #103
Opened 2024-06-21 13:56 UTC by alexvonme

The Latin corrections ended up correct ``i.e. daffodils`` to ``that isdaffodils`` so I fixed the spacing error.

The commas don't need any extra edits, since the SurroundingCommas.yml rule already corrects for them.

2024-06-21 14:47 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
there is a problem according to me

It should be either

```suggestion
  '\b(?:ie|i\.e\.),?': 'that is'
```

I don't see the point of catching a square backet made of only one item

2024-06-21 14:53 UTC, ccoVeille requested changes

2024-06-21 14:53 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
My problem here is that you went from

```
  '\b(?:eg|e\.g\.)[\s,]': for example
  '\b(?:ie|i\.e\.)[\s,]': that is
```

and you should have used

```
 '\b(?:eg|e\.g\.)\s*,?\s*': "for example "
 '\b(?:ie|i\.e\.)\s*,?\s*': "that is "
```

2024-06-21 14:54 UTC, alexvonme commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
I think I didn't like leaving the comma outside the bracket on its own, I can remove it.

However, the question can't be there because it conflicts with the rule above. Then the fix would be useless.
It would once again correct ``i.e. daffodils`` to ``that isdaffodils``

2024-06-21 14:57 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
it will catch `i.e. `, sure,, but look, it will add a space at the end

2024-06-21 14:59 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
but once again, don't reinvent the wheel, look at official packages and copy paste

https://github.com/errata-ai/Google/blob/28adc48796277429c7d0cc80932569c5e7b0c360/Google/Latin.yml#L4

2024-06-21 14:59 UTC, alexvonme commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
``i.e. `` is already caught by the rule above it though? The rule above corrects it with proper spacing.

2024-06-21 15:10 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
well, the more I look at the Google's regexp, the more I'm doubtful

there is one thing interesting to use anyway, it's the fact there could be a coma or a semicolon, it's very frequent with Latin expression

https://github.com/search?q=language%3AMarkdown+%22+i.e.%3B%22&type=code

2024-06-21 17:21 UTC, alexvonme commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
Is there a particular reason why you write the swap rules like:
``'a': "b"``
Mine generally are: 
``'a': 'b'``

2024-06-21 17:40 UTC, alexvonme commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
@ccoVeille, I'm hesitant with your suggestion. While it reduces the rules from 4 to 2, it also points to errors where it shouldn't since anything after ``e.g`` is now a problem, such as ``e.g.z``. I realize that such an expression is hardly acceptable, but this is a rule where the level is "error" and therefore requires the upmost precision.

@tbazant, I tried to maintain the rule as it is by limiting it only to spaces and commas, but I may have been over-zealous in doing so. Can we expand it to include practically any character that may come after ``e.g`` or ``i.e.``? I'd rather act with your blessing.

2024-06-21 18:10 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
> Is there a particular reason why you write the swap rules like:
> ``'a': "b"``
> Mine generally are: 
> ``'a': 'b'``

They are equivalent, no real reason to use one or another

2024-06-21 18:12 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
> @ccoVeille, I'm hesitant with your suggestion. While it reduces the rules from 4 to 2, it also points to errors where it shouldn't since anything after ``e.g`` is now a problem, such as ``e.g.z``. I realize that such an expression is hardly acceptable, but this is a rule where the level is "error" and therefore requires the upmost precision.

That's right. I think you should consider maintaining files used for tests in your repository

2024-06-21 18:29 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
Please try this and let me know

```yaml
'\b(?:ie|i\.e\.)\s*[,;]?\s+': 'that is '
```

I think it should catch the examples you spotted.

2024-06-21 20:22 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.e\.)[,]': 'that is'
the last one had issue

The more I try, the uglier the regexp becomes

```yaml
 '\b(?:ie[,;]\s*|i\.e\.\s*[,;\s]+)\s+': 'that is '
 '\b(?:eg[,;]\s*|e\.g\.\s*[,;\s]+)\s+': 'for example '
```

It's important to focus on a test document, that will reference what you expect to catch
```
Whatever, i.e., foo
Whatever, i.e.; foo
Whatever, i.e. foo

Whatever, ie., foo
Whatever, ie.; foo
Whatever, ie. foo

Whatever, ie, foo
Whatever, ie; foo
Whatever, ie foo
Whatever, ie foo


Nothing should match after this line:
Whatever, ie.z foo
Ireland TLD is .ie
Whatever, ie
Internet Explorer's nickname was IE.
```

You approach to split on multiple line was good

2024-06-22 19:31 UTC, ccoVeille commented
Hi guys. The regexp might be difficult to fox by your own.

What about reporting a bug issue to vale Google rules, pointing the issues you found with them

2024-06-22 19:37 UTC, ccoVeille commented
Found this

https://github.com/splunk/vale-splunk-style-guide/blob/main/styles%2FSplunk%2FLatin.yml

Please have a look at this vale repository

2024-06-22 19:58 UTC, alexvonme commented
> Found this
> 
> https://github.com/splunk/vale-splunk-style-guide/blob/main/styles%2FSplunk%2FLatin.yml
> 
> Please have a look at this vale repository

Yes, I saw that one, but it's not necessary in our case. SUSE doesn't seem to care much for most of them and seems to explicitly allow ``via``. We only need to fix ``i.e.`` and ``e.g.``

2024-06-22 20:01 UTC, alexvonme commented
@ccoVeille How about this:

```
  '\b(?:eg|e\.g\.|i\.[\s]e\.)[\s]': 'for example '
  '\b(?:eg|e\.g\.|i\.[\s]e\.)[?:,|.|;]': 'for example'
  '\b(?:ie|i\.e\.|i\.[\s]e\.)[\s]': 'that is '
  '\b(?:ie|i\.e\.|i\.[\s]e\.)[?:,|.|;]': 'that is'
```

It could be shorter, yes. However, this is easy to read and configure catches all possible errors.

The only false positive problem is the .ie TLD, which we'll need to add an exception for. Other than that, I'm not worried about catching IE as an abbreviation of Internet Explorer, since its obscurity ensures most people nowadays refer to it by its full name rather than its abbreviation.

2024-06-22 20:19 UTC, ccoVeille commented
Your regexp can be simplified
```yaml
'\b(?:eg|e\.g\.|i\.[\s]e\.)[\s]': 'for example ' '\b(?:eg|e\.g\.|i\.[\s]e\.)[?:,|.|;]': 'for example' '\b(?:ie|i\.e\.|i\.[\s]e\.)[\s]': 'that is ' '\b(?:ie|i\.e\.|i\.[\s]e\.)[?:,|.|;]': 'that is' 
```
Something within `[]` is a list character that could match. So it's not needed when only one character is in it. So `[\s]` = `\s`

Then 

`(?:ie|i\.e\.|i\.[\s]e\.)[\s]`

Means this

`(?:ie|i\.e\.|i\.\se\.)\s`

Then `i\.e\.|i\.\se\.` means i.e. with or without a space

So it's

`(?:ie|i\.\s?e\.)\s`

Then about

'\b(?:eg|e\.g\.|i\.[\s]e\.)[?:,|.|;]':

I have a problem with `[?:,|.|;]` it's a `[]` not a `()`, so there is no `?:` or `|` operators. And dot must be escaped.

So it should be `[,\.;]`

2024-06-22 20:24 UTC, ccoVeille commented
Here is what I would suggest

```yaml
'\b(?:eg|e\.\s?g\.)\s': 'for example ' '
b(?:eg|e\.\s?g\.)\s*[,\.;]':'for example' '\b(?:ie|i\.\s?e\.)\s': 'that is '
'\b(?:ie|i\.\s?e\.)\s*[,\.;]': 'that is' 
```

2024-06-22 20:47 UTC, ccoVeille commented
Please have a look here if you wsjt to understand

https://regexr.com/82036

2024-06-22 20:47 UTC, ccoVeille commented
Please note I edited my suggested regexp in my previous post

2024-06-23 04:16 UTC, ccoVeille commented
I now realize. I'm unsure that negative look ahead I'm suggesting to use is not supported in standard Go regexp package.

I'll have to check vale code, and suggest using a library to support it, but it may require some changes in vale code.

2024-06-23 06:25 UTC, ccoVeille commented
I checked vale use a fork of a regexp2 lib.

So it should be OK.

Please test and let me know.

I asked maintainers if they could bump the library to get new feature we don't need right now, but that could be used later

2024-06-23 19:22 UTC, alexvonme commented
@ccoVeille I tested it around and understood the overlap your last edit fixed. Thanks, as always. Just the TLD exception left.

@tbazant, sorry if this became too complicated.

2024-06-23 19:24 UTC, ccoVeille commented
Regexp are uneasy. If you want and need to catch something. The regexp is either simple and it doesn't catch everything needed, of at least the cases no one thought about are not working, or the regexp is complicated, but it works

2024-06-25 13:53 UTC, tbazant commented
I've added Latin test files, `Latin-good.txt` does not pass with the current setup

2024-06-25 14:01 UTC, tbazant commented
I've added 2 test files for Latin + minor updates to the config. Latin-good.txt fails, its content is matched :-(

2024-06-25 14:12 UTC, alexvonme commented
> The only false positive problem is the .ie TLD, which we'll need to add an exception for. Other than that, I'm not worried about catching IE as an abbreviation of Internet Explorer, since its obscurity ensures most people nowadays refer to it by its full name rather than its abbreviation.

@tbazant I'd argue that we only really need the first 2 lines of ``Latin-good.txt``.

2024-06-25 14:24 UTC, alexvonme commented
An alternative Latin-good.txt might be:
```
www.example.ie/about
https://example.eg/faq
The ie.z was not functional
```

2024-06-25 14:47 UTC, alexvonme commented
(I would like to note here that my deep appreciation for Egypt and Ireland is the reason I'm trying to add the exception)

@ccoVeille Do you have an idea on how to write the exception? I've been trying with multiple regex rules that have all failed to exclude the domains.

2024-06-25 15:56 UTC, ccoVeille commented on common/Latin.yml
> +  '\b(?:ie|i\.\s?e\.)\s*[,\.;]': 'that is'
you have to prefix ie (and eg) with a [negative look behind](https://www.regular-expressions.info/lookaround.html)

Said otherwise, the character before ie cannot be a dot

```suggestion
  '\b(?:(?<!.)eg|e\.\s?g\.)\s+(?![,\.;])': 'for example '
  '\b(?:(?<!.)eg|e\.\s?g\.)\s*[,\.;]': 'for example'
  '\b(?:(?<!.)ie|i\.\s?e\.)\s+(?![,\.;])': 'that is '
  '\b(?:(?<!.)ie|i\.\s?e\.)\s*[,\.;]': 'that is' 
```

https://regexr.com/8239f

regexp are so fun an easy to read

2024-06-25 15:57 UTC, ccoVeille commented
> (I would like to note here that my deep appreciation for Egypt and Ireland is the reason I'm trying to add the exception)
> 
> @ccoVeille Do you have an idea on how to write the exception? I've been trying with multiple regex rules that have all failed to exclude the domains.

I suggested a change, please let me know

https://github.com/openSUSE/suse-vale-styleguide/pull/103/files#r1653107808

2024-06-25 16:19 UTC, alexvonme commented on common/Latin.yml
> +  '\b(?:ie|i\.\s?e\.)\s*[,\.;]': 'that is'
The new rules miss out on the last 2 sections of the test file.

2024-06-25 20:00 UTC, tbazant reviewed
Fixed indent + removed empty lines

2024-06-25 20:00 UTC, tbazant commented on common/Latin.yml
> +   '\b(?:(?<!\.)ie|i\.\s?e\.)\s*[,\.;]': 'that is'
```suggestion
  '\b(?:(?<!\.)eg|e\.\s?g\.)\s+(?![,\.;])': 'for example '
  '\b(?:(?<!\.)eg|e\.\s?g\.)\s*[,\.;]': 'for example'
  '\b(?:(?<!\.)ie|i\.\s?e\.)\s+(?![,\.;])': 'that is '
  '\b(?:(?<!\.)ie|i\.\s?e\.)\s*[,\.;]': 'that is' 
```

2024-06-25 20:00 UTC, tbazant commented on tests/Latin-bad.txt
> +
```suggestion
```

2024-06-25 20:00 UTC, tbazant commented on tests/Latin-bad.txt
> +
```suggestion
```

2024-06-25 20:00 UTC, tbazant commented on tests/Latin-bad.txt
> +
```suggestion
```

2024-06-25 20:00 UTC, tbazant commented on tests/Latin-bad.txt
> +
```suggestion
```

2024-06-25 20:06 UTC, tbazant commented
I've applied the latest suggestion but still all sentences in `Latin-good.txt` are matched. BTW if we keep the rule that the bad test files have exactly 1 error on each line, then
```
vale --config EXAMPLE.vale.ini --output line tests/Latin-bad.txt | wc -l
```
has to match
```
cat tests/Latin-bad.txt | wc -l
```

2024-06-25 20:17 UTC, ccoVeille commented
Regexp are thought, really.

Splitting the regexp in multi lime might help

Like moving the `ie` on one line, and the `i.e.` on another, for test purpose. You will see what match and what doesn't.

Maybe the negative look behind break everything for all the regexp.

I'm still on a phone, cannot help yet

2024-06-27 13:51 UTC, tbazant commented
i replaced all the complex i.e rules with
```
  '\b(?:i\.\s?e\.)': 'that is' # i.e. with possible whitespaces inbetween
  '\b(?:ie\.\s+)': 'that is' # ie. followed by whitespaces
  '\b(?:ie\.(?=[;,]))': 'that is' # ie. followed by ; or ,
  '\b(?:ie[\t\f\r ])': 'that is' # ie followed by whitespaces but not newline
  '\b(?:ie(?=[;,]))': 'that is' # ie followed by ; or ,
```
and set `ignorecase: false`
which makes all test pass. should i update the PR's suggestion swith my findings?

2024-06-27 14:00 UTC, alexvonme commented
> i replaced all the complex i.e rules with
> 
> ```
>   '\b(?:i\.\s?e\.)': 'that is' # i.e. with possible whitespaces inbetween
>   '\b(?:ie\.\s+)': 'that is' # ie. followed by whitespaces
>   '\b(?:ie\.(?=[;,]))': 'that is' # ie. followed by ; or ,
>   '\b(?:ie[\t\f\r ])': 'that is' # ie followed by whitespaces but not newline
>   '\b(?:ie(?=[;,]))': 'that is' # ie followed by ; or ,
> ```
> 
> and set `ignorecase: false` which makes all test pass. should i update the PR's suggestions with my findings?

We can't set ignorecase to false. A lot of people literally start their sentences with ``IE``.

2024-06-27 14:04 UTC, alexvonme commented
> We can't set ignorecase to false. A lot of people literally start their sentences with `IE`.

If the reason you set ignorecase to false is to except IE for Internet Explorer, I really don't think it's necessary. I have not in the last decade seen anyone refer to it as IE. It's not used anymore, so people don't use its abbreviation.

2024-06-27 14:17 UTC, ccoVeille commented
> We can't set ignorecase to false. A lot of people literally start their sentences with `IE`.

maybe, you could use `ignorecase:false` and define all the variations you need, but exclude IE capital

```yaml
ignorecase:false
map:
  '\b(?:[iI]i\.\s?[eE]\.)': 'that is' # i.e. with possible whitespaces inbetween
  '\b(?:[iI][eE]\.\s+)': 'that is' # ie. followed by whitespaces
  '\b(?:[iI][eE]\.(?=[;,]))': 'that is' # ie. followed by ; or ,
  '\b(?:ie[\t\f\r ])': 'that is' # ie followed by whitespaces but not newline, here IE is excluded
  '\b(?:[iI][eE](?=[;,]))': 'that is' # ie followed by ; or ,
```

2024-06-27 15:10 UTC, tbazant reviewed
Simplified complex i.e. regexps

2024-06-27 15:10 UTC, tbazant commented on common/Latin.yml
> +  '\b(?:ie|i\.\s?e\.)\s+(?![,\.;])': 'that is '
```suggestion
```

2024-06-27 15:10 UTC, tbazant commented on common/Latin.yml
> +  '\b(?:(?<!\.)ie|i\.\s?e\.)\s+(?![,\.;])': 'that is '
```suggestion
```

2024-06-27 15:10 UTC, tbazant commented on common/Latin.yml
> +  '\b(?:(?<!\.)ie|i\.\s?e\.)\s*[,\.;]': 'that is'
```suggestion
  '\b(?:i\.\s?e\.)': 'that is' # i.e. with possible whitespaces inbetween
  '\b(?:ie\.[\t\f\r ]+)': 'that is' # ie. followed by whitespaces but a newline
  '\b(?:ie\.(?=[;,]))': 'that is' # ie. followed by ; or ,
  '\b(?:ie[\t\f\r ])': 'that is' # ie followed by whitespaces but a newline
  '\b(?:ie(?=[;,]))': 'that is' # ie followed by ; or ,


```

2024-06-27 15:16 UTC, alexvonme commented
I fully agree with your need to finally be done with this one. Though, I think I made the last change. If you're okay with it, please merge.

2024-06-27 15:25 UTC, merged