Update Contractions.yml
openSUSE/suse-vale-styleguide pull request #107
Opened 2024-06-24 17:20 UTC by alexvonme

I added "can not" to phrases that should be corrected to "cannot"

I also added the 'll, 've and 're contracted forms for we, they and you.

2024-06-24 21:46 UTC, ccoVeille commented on common/Contractions.yml
> +  you've: you have
I know I found some people using backtrick instead of simple quote.

They should be ashamed but they aren't

https://github.com/search?q=language%3AMarkdown+%22can%60t%22&type=code

There are also the `space` guys

https://github.com/search?q=language%3AMarkdown+%22can+t+%22&type=code

So each line should use a ``['` ]`` I'm unsure if the backstick should be escaped or not

And finally the lazy ones

https://github.com/search?q=language%3AMarkdown+%22+cant+%22&type=code

So you will have to use ``can['` ]?t|cannot``

2024-06-25 09:53 UTC, alexvonme commented on common/Contractions.yml
> +  you've: you have
While I don't fully share your dismay, I'm quite astonished, especially by people who use spaces. Should I just add that to all of them except for ``we'll``. There, I guess,  ``we['`]ll`` will suffice.

2024-06-25 10:45 UTC, ccoVeille commented on common/Contractions.yml
> +  you've: you have
I think so

but please also consider these other crazy people

https://github.com/search?q=language%3AMarkdown+%22canot%22&type=code

[canot](https://fr.wikipedia.org/wiki/Canot) is a French word meaning a [rowing boat](https://www.wordreference.com/fren/canot)
so it could be a false positive, but I'm sure no one using it in documentation files would talk about a  rowing boat

But please consider the false positive for each of them maybe

2024-06-25 10:46 UTC, ccoVeille commented on common/Contractions.yml
> +  you've: you have
we also have these crazy people

https://github.com/search?q=%22+couldt+%22&type=code

2024-06-25 10:49 UTC, ccoVeille commented on common/Contractions.yml
> +  you've: you have
these one are somehow counter-examples

 they could be reviewed outside the current regexp, and only the one that are frequent in term of frequency should be added

```yaml
swap:
  can['` ]?t|can not: cannot
  couldn['` ]?t: could not
  
  canot: cannot # typo
  couldt: could not # typo
```

Maybe in a different rules btw

2024-06-25 10:52 UTC, alexvonme commented on common/Contractions.yml
> +  you've: you have
We don't need to fix either one of those since they're both covered by ``spelling`` from actions.

2024-06-25 10:55 UTC, ccoVeille commented on common/Contractions.yml
> +  you've: you have
good point. There is always a limit to fix

2024-06-26 18:36 UTC, alexvonme commented
@tbazant this pull request seems done, you can merge it in case you're agreed with the changes.

2024-06-26 19:07 UTC, ccoVeille requested changes

2024-06-26 19:07 UTC, ccoVeille commented on common/Contractions.yml
> +  it['` ]?s: it is
`its`(possessive) will get caught. It's a problem 

```suggestion
  it['` ]s: it is # its would be false negative
```
remove the `?` and add an inline comment

2024-06-26 19:07 UTC, ccoVeille commented on common/Contractions.yml
> +  we['` ]?re: we are
`were` (be verb in past) will get caught, remove the `?` and add an inline comment

2024-06-27 10:10 UTC, alexvonme commented on common/Contractions.yml
> +  we['`]ll: we will
Good idea, I'll add that with were as well.

2024-06-27 10:11 UTC, alexvonme commented on common/Contractions.yml
>  action:
its should not be included

2024-06-27 10:12 UTC, alexvonme commented on common/Contractions.yml
> +  it['` ]?s: it is
The ``its`` possessive isn't desired anyway, SUSE doesn't allow inanimate objects to receive possessives.

2024-06-27 10:13 UTC, alexvonme commented on common/Contractions.yml
> +  we['` ]?re: we are
Yeah, will add a comment for that one, same with ``well``.

2024-06-27 10:17 UTC, alexvonme commented
@tbazant can I just make this one an error? SUSE seems clear in its repeated disapproval of contractions and possessives.

2024-06-27 12:05 UTC, dariavladykina reviewed
LGTM, and I added a comment on the use of 'its'. Thanks!

2024-06-27 12:10 UTC, tbazant reviewed
`its` remains to be resolved

2024-06-27 12:10 UTC, tbazant commented on common/Contractions.yml
> +  shouldn['` ]?t: should not
```suggestion
  shouldn['` ]?t: should not
  wouldn['` ]?t: would not
```

2024-06-27 12:20 UTC, merged

2024-06-27 12:27 UTC, alexvonme commented on common/Contractions.yml
> +  it['` ]?s: it is
I agree. The overwhelming majority of the use of ``its`` is undesirable. 

> ```
> To run a new command and start tracing its system calls
> ```

For the sentence above, the existing documentation has 2 relevant rules:
- That we avoid passive language
- That we avoid ascribing possessives to inanimate objects

Both can be satisfied by using ``the relevant``, ``the resulting``, ``the subsequent`` or even ``the ensuing`` instead of ``its`` there. I believe, we should move on with this. Worst case scenario, the rule is easy to update with an example present anyway.

2024-06-27 12:31 UTC, dariavladykina commented on common/Contractions.yml
> +  it['` ]?s: it is
IMO, it is fine to use the possessive pronoun like this for inanimate objects in English. I'm not in favor of replacing it with officious-sounding 'resulting' or 'subsequent'. Here's an example: _Neither SUSE LLC, its affiliates, the authors nor the translators shall be held liable for possible errors or the consequences thereof._

2024-06-27 12:41 UTC, alexvonme commented on common/Contractions.yml
> +  it['` ]?s: it is
I see, we often use ``the relevant`` in cases where I've seen it. ``subsequent`` is a phonetically lovely word, but definitely not a great fit for documentation.