Create Slash.yml
openSUSE/suse-vale-styleguide pull request #111
Opened 2024-06-30 15:31 UTC by alexvonme

I added the slash rule.

I also inelegantly added exceptions for both "AMD64/Intel 64" and "Wi-Fi/Bluetooth card" since their use was suggested in the style guide.

2024-06-30 15:45 UTC, ccoVeille commented
I'm a bit afraid this rule would need a lot of maintenance to add every exception needed

At least you used suggestion level

2024-06-30 15:49 UTC, ccoVeille commented
I will try to run it on my code base.

But I can at least can think about  CPU architecture:

- linux/amd64
- linux/arm64
- …

More example here 

https://docs.docker.com/build/building/multi-platform/

2024-06-30 15:51 UTC, alexvonme commented
> I'm a bit afraid this rule would need a lot of maintenance to add every exception needed
> 
> At least you used suggestion level

Absolutely, which is why I put suggestion as the level and added a generalized message.

2024-06-30 16:02 UTC, alexvonme commented
> I will try to run it on my code base.
> 
> But I can at least can think about CPU architecture:
> 
> * linux/amd64
> * linux/arm64
> * …
> 
> More example here
> 
> https://docs.docker.com/build/building/multi-platform/

Different organizations may have different principles. In this case, SUSE appears to approach acceptable slashes cautiously. So, for now at least, I don't think we should add anything that wasn't explicitly allowed in the style guide to rule here.

I thought about adding a lot of other stuff as well, but we should consider those within jargonLint/jargonLint/discussions/33. If a larger rule there becomes useful, then we can suggest it here as well.

2024-06-30 16:17 UTC, ccoVeille commented
Make sense

2024-06-30 17:03 UTC, ccoVeille requested changes

2024-06-30 18:31 UTC, ccoVeille commented on common/Slash.yml
> +  - 'SSL/TLS'
please add at least the following
- N/A
- R/W

any variation of something per seconds:
- MB/s
- kb/s
- km/h

Now I have reviewed what matches the regexp, I would simply discourage to use it. you will have tons of false-positive reported as suggestion

2024-07-01 01:42 UTC, alexvonme commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
> ```
> 1.6.18 / 2019-04-26
> ```

This one is easy to add to exceptions, but I really don't think it's necessary, since these should be rare and concentrated. Furthermore, I'm not sure if this should even be considered a false positive, since this is not how SUSE wants slashes to be used or suggests versioning be done.

> ```
> - [github/azu](https://github.com/azu)
> - [twitter/azu_re](http://twitter.com/azu_re)
> ```

Here the suggestion won't match the link but will instead match the ``github/azu`` part which I don't think we should take into account. Once more, SUSE doesn't seem to want slashes used in this manner either. Again, I don't think this is a false positive in the first place.

My interpretation here, even stronger than in the case above, is that SUSE would prefer [azu](https://github.com/azu) or [azu at GitHub](https://github.com/azu) over [github/azu](https://github.com/azu) anyway.

> ```
> + [github/jonschlinkert](https://github.com/jonschlinkert)
> + [twitter/jonschlinkert](http://twitter.com/jonschlinkert)
> ```

The problem is the same as above.

2024-07-01 01:45 UTC, alexvonme commented on common/Slash.yml
> +  - 'SSL/TLS'
I can add these now, and add more exceptions over the week. The rule will still not be completely correct which should be acceptable since we just want it to warn users not to use slashes. It's not an error so even if there are false positives, it shouldn't interfere with the pipeline or GitHub actions.

2024-07-01 01:58 UTC, alexvonme commented
@ccoVeille I understand your frustration with the rule's current limitations, but I'd still argue that the rule serves its purpose of warning users not to use slashes. It is not perfectly thorough, though for such a simple rule, that doesn't strike me as a problem. Slash rules are fairly popular in other Vale repositories as well, and most of them will prompt more false positives than this one.

For my part, I used it in Kanidm, which is under openSUSE and the rule was useful. Filenames as in ``/etc/foo`` were overwhelming excluded, so were links, while the rule correctly identified a lot of occasions where slashes shouldn't have been used. As such, I believe this rule would still be an asset to projects under SUSE and openSUSE, since it non-intrusively warns for a clear rule in the style guide.

I'd also prefer not to dwell too much on the rule, like we did in Latin.yml(#103). This rule isn't perfect and, in the short term at least, that should be acceptable.

2024-07-01 02:13 UTC, alexvonme commented on common/Slash.yml
> +  - 'Fi/Bluetooth' # To avoid matching "Wi-Fi/Bluetooth card"
Doesn't work? Furthermore, I don't think we need to worry about Lofi/Bluetooth since that's not a common phrase.

2024-07-01 02:16 UTC, alexvonme commented on common/Slash.yml
> +  - 'SSL/TLS'
Please check the new commit, I've added the important ones.

2024-07-01 05:07 UTC, ccoVeille commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
I understand. I agree with you.

I'll try to find obvious false positive and reports them to you here.

2024-07-01 05:12 UTC, ccoVeille commented on common/Slash.yml
> +  - 'Fi/Bluetooth' # To avoid matching "Wi-Fi/Bluetooth card"
Because the rule is not using nonword:true

I don't think WiFi/Bluetooth will be caught.

Adding \b everywhere might be needed if you enable it.

2024-07-01 05:32 UTC, ccoVeille commented on common/Slash.yml
> +  - 'read/write'
R/W is also a common way to write it.

2024-07-01 06:05 UTC, ccoVeille commented on common/Slash.yml
> +message: "Only use slashes with filenames, links and terms such as TCP/IP."
Please rephrase to add the %s somewhere, because without it's very difficult to spot the issue

```suggestion
message: "%s: Only use slashes with filenames, links and terms such as TCP/IP."
```

2024-07-01 06:05 UTC, ccoVeille commented on common/Slash.yml
> +message: "Only use slashes with filenames, links and terms such as TCP/IP."
use an Oxford list
```suggestion
message: "Only use slashes with filenames, links, and terms such as TCP/IP."
```

2024-07-01 08:07 UTC, ccoVeille commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
I'm worried about something

This rule allows spaces, and it's OK.

But none of the exception list the fact something with a space could have been detected.

2024-07-01 08:07 UTC, ccoVeille commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
This rule needs a huge list of examples in unit tests.

2024-07-01 09:29 UTC, alexvonme commented on common/Slash.yml
> +message: "Only use slashes with filenames, links and terms such as TCP/IP."
SUSE [doesn't allow](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-comma) the Oxford comma.

2024-07-01 09:30 UTC, alexvonme commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
I don't think that's an issue since ``TCP/IP`` is suggested, whereas ``TCP / IP`` is disallowed anyway.

2024-07-01 09:33 UTC, alexvonme commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
For now, 10 lines or so should suffice, since that is the extent we're willing to exclude from the rule.

2024-07-01 09:33 UTC, ccoVeille commented on common/Slash.yml
> +message: "Only use slashes with filenames, links and terms such as TCP/IP."
OK.

2024-07-01 09:40 UTC, ccoVeille commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
Maybe you should add in comment in this rules files, a few ones that are especially targeted by the rules.

I'm afraid you will get many people reporting they want to support Debian/Ubuntu

Or, you could write another rule aside this one with the very popular ones you want to catch and suggest how to replace them in the suse way.

Like a jargonLint rules would do

2024-07-01 09:53 UTC, alexvonme commented on common/Slash.yml
> +  - 'Fi/Bluetooth' # To avoid matching "Wi-Fi/Bluetooth card"
> I don't think WiFi/Bluetooth will be caught.

It's caught, also we'll later have additions from the appendixes as a rule as well. There we can add a correction for all imperfect versions of "Wi-Fi/Bluetooth".

2024-07-01 10:47 UTC, ccoVeille approved these changes
A few more example to avoid issues if a refactoring is made

2024-07-01 10:47 UTC, ccoVeille commented on tests/Slash-good.txt
> +Wi-Fi/Bluetooth
```suggestion
Wi-Fi/Bluetooth
WiFi/Bluetooth
```

2024-07-01 10:47 UTC, ccoVeille commented on tests/Slash-good.txt
> +10/1990
```suggestion
10/1990
24/7
```

Adding 24/7 would be interesting as it's not a date that could be altered if a refactoring of date was made

2024-07-01 10:50 UTC, ccoVeille commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
@alexvonme what do you think about this one?

2024-07-01 10:52 UTC, ccoVeille commented on common/Slash.yml
> +message: "Only use slashes with filenames, links and terms such as TCP/IP."
@alexvonme you resolved, but I don't see changes on the PR.

Did I miss something?

2024-07-01 12:05 UTC, alexvonme commented on tests/Slash-good.txt
> +10/1990
I don't think SUSE allows 24/7.

2024-07-01 12:09 UTC, alexvonme commented
@tbazant this branch seems ready to merge. I've also added test files, sorry for neglecting those in earlier rules.

2024-07-01 12:29 UTC, ccoVeille commented on tests/Slash-good.txt
> +10/1990
Suse allows nothing 🤭🙄😅

2024-07-01 12:43 UTC, alexvonme commented on common/Slash.yml
> +  - '(?<!/)\w+\s?\/\s?\w+'
I honestly think that adding SUSE/openSUSE or Debian/Ubuntu type exceptions would be useful. However, we should probably test and explore these in jargonLint. SUSE doesn't explicitly allow them for now, so that's where I prefer to leave it in the rule here.

2024-07-01 12:45 UTC, tbazant commented
@dariavladykina do we have strong opinions about using slashes? if so, does it align with suggested changes?

2024-07-01 12:47 UTC, alexvonme commented on common/Slash.yml
> +message: "Only use slashes with filenames, links and terms such as TCP/IP."
Should be better now.

2024-07-01 12:53 UTC, dariavladykina commented on tests/Slash-good.txt
> +GB/s.
Does the full stop belong here?

2024-07-01 12:55 UTC, dariavladykina commented
All of these additions for good and bad slash uses seem OK to me. Do we also have a rule to not use space around slashes? I.e. to avoid `slash / slash`? Thanks!

2024-07-01 12:59 UTC, alexvonme commented on tests/Slash-good.txt
> +GB/s.
That's kind of a funny addition we need to make to long list type test where at least every tenth or so item should end with a period. Otherwise, we can come across issues regarding the VS Code extension (as in ChrisChinchilla/vale-vscode/issues/46) or interact with other rules, such as those concerning sentence length.

Alternatively, in long list type tests, we can end each line with a period, but the difference is immaterial.

2024-07-01 13:02 UTC, alexvonme commented
> All of these additions for good and bad slash uses seem OK to me. Do we also have a rule to not use space around slashes? I.e. to avoid `slash / slash`? Thanks!

Yes the regexp matches and therefore disallows them, which I had to write for my main project Kanidm, where we previously used and need to correct a lot of those.
```
'(?<!/)\w+\s?\/\s?\w+'
```
The ``\s?`` parts in specific satisfy that need.

2024-07-01 13:03 UTC, dariavladykina approved these changes
LGTM!

2024-07-01 13:31 UTC, merged