Create AcronymApostrophe.yml
openSUSE/suse-vale-styleguide pull request #96
Opened 2024-06-18 18:26 UTC by alexvonme

I added a rule to check if any acronyms received an apostrophe.

It currently works properly, but I concede that both the message and token could be better written. Please feel free to suggest edits.

2024-06-18 19:13 UTC, ccoVeille approved these changes
LGTM 👍

The only problem I see with vale rules is somehow the inability to define unit tests for them, and something that could be added to a CI workflow

2024-06-18 19:18 UTC, ccoVeille requested changes

2024-06-18 19:18 UTC, ccoVeille commented on common/AcronymApostrophe.yml
> +  - ^[A-Z]{2,}'(?:s|es|ies)
```suggestion
  - ^[A-Z]{2,}'(?:s|es|ies)?
```

Maybe this to catch:
- invalid apostrophe: `USA' army`
- acronym ending with S, that may be used like this: `ISS' members`

2024-06-18 19:18 UTC, ccoVeille commented on common/AcronymApostrophe.yml
> +ignorecase: true
The ignore case seems a problem to me

Won't you catch lower case top?

2024-06-19 09:44 UTC, alexvonme commented on common/AcronymApostrophe.yml
> +ignorecase: true
Yeah, thanks. I think I got too used to writing that down for other rules.

2024-06-19 09:50 UTC, alexvonme commented on common/AcronymApostrophe.yml
> +  - ^[A-Z]{2,}'(?:s|es|ies)
Good idea, I've added this functionality too.

2024-06-19 09:52 UTC, alexvonme commented
Thank you very much @ccoVeille, I've updated the pull request.

2024-06-19 14:17 UTC, merged